version: "3.0"

services:

  postgres:
    image: postgres
    ports:
      - "5000:5432"
    environment:
      - POSTGRES_PASSWORD=7554
      - POSTGRES_DB=diary_bot

  spring-boot-app:
    image: diary-bot
    ports:
      - "8000:8000"
    network_mode: host

networks:
  localhost: