version: "3.0"

services:

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=7554
      - POSTGRES_DB=diary_bot

  #spring-boot-app:
    #image: registry.gitlab.com/al3ksus/diarybot
    #ports:
    #  - "8080:8080"
    #environment:
    #  - TZ=Europe/Moscow
    #network_mode: host

#networks:
#  localhost: