package com.example.DiaryBot.model.enums;


public enum BotState {
    DEFAULT, SET_TEXT_REMINDER, SET_TIME_REMINDER, SCHEDULE,
    DELETE_REMINDER, EDIT_REMINDER, EDIT_TIME_REMINDER, EDIT_TEXT_REMINDER
}
