package com.example.DiaryBot.model.enums;


public enum BotState {
    DEFAULT, SET_REMINDER_TEXT, SET_REMINDER_TIME, SCHEDULE,
    DELETE_REMINDER, EDIT_REMINDER, EDIT_REMINDER_TIME, EDIT_REMINDER_TEXT
}
