telegram:
  bot-name: Dailu_Helper_Bot
  bot-token: 5620340450:AAEStJhaE1cd9x8VJjtyWIcAfcje1LsWjVg
  api-url: https://api.telegram.org
  webhook-path: https://616c-85-113-138-225.eu.ngrok.io

server:
    port: 8080